language: java

jdk:
  - oraclejdk8

services:
  - mysql

sudo: false

before_install:
  - mysql -e 'CREATE DATABASE adebar;'

before_script:
  - cp src/main/resources/application-travis.properties src/main/resources/application.properties

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
      - "$HOME/.m2"
      - "$HOME/.sonar/cache"

addons:
  sonarcloud:
    organization: "portux-github"
    token:
      secure: "XeDVd803azAASKgFZTVyAdUrCHsXNy2OlitlPVj8/nYiX3SYwI+1Sn/yAigRckDlpRAecIUNI/XbYUaZEpOJHouMEzWfMfGQM2dUFYEY1AhDIM35ugW8oa3801SaqNywGfFeSQ9nnD2Du3mVGhXMISFGANvM9K2QpqeyFxW+2DrVJ6qf+r7oSbRWIHlAovzS7w2qxwxFpmzoP8Cfq+MHHC36gNUclYsmP9A+5LF9ahoKJdMnn8lzcnfCBCKTs5CNaajeon96OrvNPwX/3TCzAltel3ilkOVozJ/GQq2VLroWMMdA8bLuBJ7im7h6tILmWmOMhoTiEEElfIbCV0w+oBQ+fWTopN22Q6jylAVVPG+NXLlbys3wQKf3g/29wpayyv56Ao1JRCKbEaSiTICR4K9jSeQ3M3yb1QrkB+hZPSuEGGcAPG11s0WR5r1L1+/+5SgOEsfkUaNRv98bt7Y85DhTHLw05V2JoLwyHqVzgBLVztW5ZZ2UAtqLvt7iNHQpobdzGzKdZj5F+4j6oPzcO4Tr44JU1az+d+cCMt4GoAx1GIfK10OPw54ez9EMXSRiqUBjTIzAqYolZ4sXnlZ7awbZ2vZFWZneBGwJckfizwAc6RKKkWjeO/uJWxIoyi+q2qvf/orKcs3lOdpFqt6totVx5H+IRHvjm2BzMA+Fkbc="


notifications:
  slack:
    secure: O2F2K0E5t/XERfZzM8Q9ylyABpNtN+FM7PvYV32u/YzsqPDl6HLiXgSSqjcpj3OESMjkk6cFJTVNNxOd88BRFL26jeI5sIA76tKnTVrJrPNCf4MksIwvpeHRjgIA0Juz13nDlbJcvZuVIBn35Esl/NbbzMKgUQNqqUTzCiyk1OXjyD4nbnTG+aHs+Kpe5KMvBN5Pqp8HjlpxwcRkUa0RalK9v8c9e8zXgj2ZeJ0W2nLD05PtywMn77XlI3/HrhJMa3HLbniUMy8MVokfOcxcoBVL7UHHvbwX1HmwtiP8MB9XnLWmTadw8gB8p3x4iXdgZuG/e863QwQWNzoRdmG1vs/vT4/aKv8n5EdXxZPhio5vmDD9bIW1NuDxGs6Tzok8OguYkzjQ20Qpd5TplQHBlyQ+v797GW7Ix/fsI0nuiNerpOZ23lPPq67X61fdZIbaCtposMkUD0hhbQ64rHDVf4wHyqIxIu3+2hYojySTkfDOLvnjHIoS2klwbFk6u5ATEl5ONi3rJ4U8PVVmgjOC3xBCsoJVQciGccU3R2Ww3ZIVrqPV+tHT43WnBjwxh3hQ+TQJeALU/V8VnvoGMYB5TaJBlUNcXB2Bb5Z6EVC1i8OMcs2wPtW/TasDtu5bA6tcq/N/OaQHm38zz8A1fhieLlHoYXPm3D/xPBPTTYMxp3Y=
