language: java

jdk:
  - openjdk8

services:
  - mysql

sudo: false

before_install:
  - mysql -e 'CREATE DATABASE adebar;'

before_script:
  - cp src/main/resources/application-travis.properties src/main/resources/application.properties

cache:
  directories:
      - "$HOME/.m2"
      - "$HOME/.sonar/cache"

addons:
  sonarcloud:
    organization: "naju-sachsen"
    token:
      secure: "ALV1vE+EYdvtLf/B9F3QpRcN6tLz8FVFSEb1ZpTqpgOKCu9J5uVwK4owZypv73qKp06Ao2ixR3SLE6Bm1JmIaSQe1x3sdrMlT0b85Qr8TrnyNUUfsjyNzSaXH5ktZn3Z4Bx7D5qAF3oBohyOmHQLbJbOKrNtMdJc926Kn+FW11pEC0R+5LsYKIIfIaiMEMEBsw3l9Q7aOh9PHTV0QgQsATa04ge/4AFhFw05WCRd78PPk9ZfWhw0gZHgqKwREoXFxreczLGKk0X5hbY+hqBjNjjobWewRqnnn9TwE3uWbbfNmpduzatwJQWUKjR1Na32T9FJXfoLoZ+PXt1xCvIOeKASxjTPe1REAoucuoiLnewFnxFteMDqCksqlfy5ZwuEGnqn+Wd1nlbYolJuVTVoTcviX+e7ghbuZ1UxGmxZ/3zkqEz59z8gOmtF4H3kfMtZqoLzacG32k/O9/fBqzgAar27Pv/KGspwa8LKV2CuQWFwom8kKA0DpaiL2qVFvo7wAwYkhITnfjqDZywPfCLHfLv1N3Moq0P+S6IqId3DmeKZP3zjo/bwHhqS6dkJxoBKVpeIqZGhink8RCw2yD7XMe2YP4iNCZ1W9sL3IFMRiNQwetOqRqK2aY1+BfB1JbxeZb4kk5aPRqn/hk68cWgPFCMeFzGAGrGtdxj076azrhM="
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

notifications:
  slack:
    secure: mhI3BfgTL3gIzrV2vMlWVjZOsGawESvpfSY6tCLM+/tPfzBIq37I1vtD7zInp5dlD97WtSyorQSRYKJha7if60Jc/IPBvVfcXGc3TSvqUTchII+djpSjtu151a6EmaNDZNm4MtOWScp9JfF57bne9A9SPgTzC/1sMbaO/9ePrVyFicOMea2KrrYRnzoxQC1jgTTT26/c1w3hPG75Vk7f4V3rwJ+z9WMYDerIypGsJdUTj3xWMok2kZEUevgBqJC3Mbnf/wbCqNiprL19hs8Pj2YP7KST2e0Is2tTZkjD2WiYpyBgA4u/K6nhweP+e0ltwkwsaVz+0z2MVTa6vdY8yGtweEzAdJpqE17jJVDRPAmJNdV86VffwZ9ggwLH5BpvBmWpQ8q+9Q/HSWYDlrOyY1pyMAf6V6H3oY/7iMofcl7u5GvkseF52WbrJiwoKB61P36p4GH2y9VRZoQrXk/qvrNSRc1+cbqHpoF7LIIEsgZMihVUY//MSWEbCjXbhqyHsEtDKzqxa8xTCL5F9HOId2OhKxbfobNvYJBOUa1CmdAH9VwStPQzOFO3tGhmhslXT6KzwEw/HmzYxcY1ROyIz4Tg775GwlDt4HRviZ12kUnTTp8/HL0orvOw7rWUdou/2CgO3ZyxpGZw3wbzNxCWkQ0JF51dFurKLtHFwIlQYyo=
