language: java

jdk:
  - oraclejdk8

services:
  - mysql

sudo: false

before_install:
  - mysql -e 'CREATE DATABASE adebar;'

before_script:
  - cp src/main/resources/application-travis.properties src/main/resources/application.properties

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
      - "$HOME/.m2"
      - "$HOME/.sonar/cache"

addons:
  sonarcloud:
    organization: "portux-github"
    token:
      secure: "GTtbeIjJ6N4KDapUTJpIfYziDNKnyL2B/mBnEYYSzY0G6M7AFXm8xHQQb0NV9Tkaz7e+YsJMHcoA1JVkplcL996Y6hVXFL7IYgTuhRFaa6PgdxfY1IEx5Zp6Ojh5NudJVQyQ9z9zhXEu+SaoBXiLqOwlrFqKvSBCjdC59M35k8Hb84K7drsCzqAnVC94gjMiM60OqiyXplpWQo5dRquqgackHbqZcysZBa0u1V0fdt9pJ1BnElySHzkou3JegDEHtzTqzfb0Ksi90Ib5Uw9l/HGRLsiasfypZ15SyhV8k+I+/QnQgMJbQSnhVNWVSPPE3B3PnzaDOF6mfJs0FCrDtSkxw/tC2m3b3H16SXFSkYAngWO/3nAmlEFngjf4lTnXot6IfqkHnTVSONrNkwz1HPjEvumvCAw43VgSGjMrNl5/9mhIfDUc8FvjX+PcOe7LFKojBfwl10dicFMQNS5IAJiVlBNeyL8M5UPvwwsBqF7XCrQrQIa+B6mG/b+5grjB3+fknZHBBWuBgEFMB5cAzHmOYKNhl5DoXSF3jj4152uW2UzCWQYXzos/UGQyNK5XfTQI+GAV2DfwJHFm2DFCnF+hnmfwbrqjD1RNUHrB/ltKXfoFg3XZqGywpy3F7moiGDBUd3Gp49ccMmO1GnHayll6h0gFJRoitVk+8kTmT74="
      
notifications:
  slack:
    secure: O2F2K0E5t/XERfZzM8Q9ylyABpNtN+FM7PvYV32u/YzsqPDl6HLiXgSSqjcpj3OESMjkk6cFJTVNNxOd88BRFL26jeI5sIA76tKnTVrJrPNCf4MksIwvpeHRjgIA0Juz13nDlbJcvZuVIBn35Esl/NbbzMKgUQNqqUTzCiyk1OXjyD4nbnTG+aHs+Kpe5KMvBN5Pqp8HjlpxwcRkUa0RalK9v8c9e8zXgj2ZeJ0W2nLD05PtywMn77XlI3/HrhJMa3HLbniUMy8MVokfOcxcoBVL7UHHvbwX1HmwtiP8MB9XnLWmTadw8gB8p3x4iXdgZuG/e863QwQWNzoRdmG1vs/vT4/aKv8n5EdXxZPhio5vmDD9bIW1NuDxGs6Tzok8OguYkzjQ20Qpd5TplQHBlyQ+v797GW7Ix/fsI0nuiNerpOZ23lPPq67X61fdZIbaCtposMkUD0hhbQ64rHDVf4wHyqIxIu3+2hYojySTkfDOLvnjHIoS2klwbFk6u5ATEl5ONi3rJ4U8PVVmgjOC3xBCsoJVQciGccU3R2Ww3ZIVrqPV+tHT43WnBjwxh3hQ+TQJeALU/V8VnvoGMYB5TaJBlUNcXB2Bb5Z6EVC1i8OMcs2wPtW/TasDtu5bA6tcq/N/OaQHm38zz8A1fhieLlHoYXPm3D/xPBPTTYMxp3Y=
