language: java

jdk:
  - oraclejdk8

services:
  - mysql

sudo: false

before_install:
  - mysql -e 'CREATE DATABASE adebar;'

before_script:
  - cp src/main/resources/application-travis.properties src/main/resources/application.properties

cache:
  directories:
    - $HOME/.m2
