language: java

jdk:
  - oraclejdk8

services:
  - mysql

sudo: false

before_install:
  - mysql -e 'CREATE DATABASE adebar;'

before_script:
  - cp src/main/resources/application-travis.properties src/main/resources/application.properties

cache:
  directories:
      - "$HOME/.m2"
      - "$HOME/.sonar/cache"

addons:
  sonarcloud:
    organization: "portux-github"
    branches:
      - master
      - develop
    token:
      secure: "igcGgKleBOmdKd+/JoIugDC9c4aXsOy795r4M06GzELukAtO0/pf3Mv0C1jOxB4WT9XUxx6hgFqRvzHb0rpkoF/fHldm6IDIKiVqbQsIx6RQwktMvgEO6J5GB+wBrmkn0G/Wr+QFwCVHtA5ZgncFcjiZK+ajhA6eMi35bd1YfkJZ7UNNsmiIHFZoXQMPRMsCcML2alTMG4VB8KkA/+RrQcieXSNKlybaQfx43XCaH5u1bmcjl2GLFqsMR47bNeBe29Hn/+NrqDFkDwpBPsLQ7U+E4KSQqX+lxrWGtgpFYVp3UmFf6B/0z+UdOr7hj8nAMldJ9Ak7a7F41oQwh2x9Lyxk44B8lf5I6X42Xiav8KXdGWJFJnYaSpmNQaRhDq7FKQrNlZjWwWLalptpDTzXOxteiR0XTDg+YktJnKKankp7YFY3jWMJWZJDQYdanGRMD51OHYmWoRiMlHdtaOSwA9yxG1ukb2BXXcTz+Assn3AK23/HoVNaScQkT/GdZwkRv/ipb78BRUFAghq/xNf4CELgJ0za5A9TeUknXUEvop1IDWfa03elo4v53hzUW3OXmdmC6ubWI36cwb6k4uQRlVPUBv6jhYIpeJvQyVM0OrZSOl76KAkWN4irivx0fxYUkuWHkpCZDhBAD0TqlfkZt/xsBjIwhIaPEHGt8ZW3j3Y="
