language: java

jdk:
  - oraclejdk8

services:
  - mysql

sudo: false

before_install:
  - mysql -e 'CREATE DATABASE adebar;'

before_script:
  - cp src/main/resources/application-travis.properties src/main/resources/application.properties

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
      - "$HOME/.m2"
      - "$HOME/.sonar/cache"

addons:
  sonarcloud:
    organization: "portux-github"
    token:
      secure: "FwGOlbcznBz3BatNKvD2SY2fwNwkENfXNL8TZVF6aHRcKQgG4Yjr/5YWI5F8/ip1QsAb7jgLclLExxZdu3jSwU2Ox6lnbdBdfR9st9N4ZB/kqHC7AfUtGXodO4WMG+X/OzXtm31+Wul6tDXjfLLE1ezCZNwYwNiG/PkENqFxmGyhVQzFsIEWTKAIsfGxlkmxz8ztbKHSBsbk3fus/XGLWVkn4IPFSFV+femu5c2ajNT24dwSVUibYrp+wNqNTascpdx4tgQKq3vgPvHHxZxe0wmvWB8w8fIWXCGhII3Wi4naG494wkYk4X47s3P3njFIy3HCqs/05JC8Tu9AH0rKtLECBa3PaSFu7vZ/l8VnwyfUePrjgW/gL+DkDwFeeX2dbT9sziBsCrWCerjI5e2/jRM7zdM7zigA/z+bYNhoI1fYYixR5KXzbCwCdtSsdwioMsvFeaYlOs6VblSq6sXHvZDH8sDc3NIQeKgWULdSn8MIL5xEof8gi2Z4SYiDeT7sze85LNWn6aQjx6ED+Sn74gUzoVXImuYSq4xZQIaNT8bz+ynlqQYkeYWOHkgrhhXfM1Vnyk39/moFOAr2wla5Ra3gCJ5zC66fkJstyp4fAtppdlBlyxfkcPI8wIIKbTSOpZhfon93ogR3CGK+jZLRWRtZrKqGpF5PQFaFmuCkKWs="

notifications:
  slack:
    secure: O2F2K0E5t/XERfZzM8Q9ylyABpNtN+FM7PvYV32u/YzsqPDl6HLiXgSSqjcpj3OESMjkk6cFJTVNNxOd88BRFL26jeI5sIA76tKnTVrJrPNCf4MksIwvpeHRjgIA0Juz13nDlbJcvZuVIBn35Esl/NbbzMKgUQNqqUTzCiyk1OXjyD4nbnTG+aHs+Kpe5KMvBN5Pqp8HjlpxwcRkUa0RalK9v8c9e8zXgj2ZeJ0W2nLD05PtywMn77XlI3/HrhJMa3HLbniUMy8MVokfOcxcoBVL7UHHvbwX1HmwtiP8MB9XnLWmTadw8gB8p3x4iXdgZuG/e863QwQWNzoRdmG1vs/vT4/aKv8n5EdXxZPhio5vmDD9bIW1NuDxGs6Tzok8OguYkzjQ20Qpd5TplQHBlyQ+v797GW7Ix/fsI0nuiNerpOZ23lPPq67X61fdZIbaCtposMkUD0hhbQ64rHDVf4wHyqIxIu3+2hYojySTkfDOLvnjHIoS2klwbFk6u5ATEl5ONi3rJ4U8PVVmgjOC3xBCsoJVQciGccU3R2Ww3ZIVrqPV+tHT43WnBjwxh3hQ+TQJeALU/V8VnvoGMYB5TaJBlUNcXB2Bb5Z6EVC1i8OMcs2wPtW/TasDtu5bA6tcq/N/OaQHm38zz8A1fhieLlHoYXPm3D/xPBPTTYMxp3Y=
